apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-react-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins-react-deploy
  template:
    metadata:
      labels:
        app: jenkins-react-deploy
    spec:
      containers:
        - name: nginx
          image: dowk0331/react-deploy:jenkins-test
          ports:
            - containerPort: 80
              name: web
          imagePullPolicy: Always
          env:
            - name: DATE
              value: 'DATE_STRING'
      imagePullSecrets:
        - name: my-secret