apiVersion: v1
kind: Service
metadata:
  name: jenkins-react-service
  labels:
    app: jenkins-react-deploy
spec:
  ports:
    - name: web
      port: 80
      targetPort: 80
  selector:
    app: jenkins-react-deploy
  type: NodePort
